/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prototipo2p;

/**
 *
 * @author SEBAS
 */
public class PROCESOS extends javax.swing.JInternalFrame {

    /**
     * Creates new form PROCESOS
     */
    public PROCESOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuAsignacionPercepciones = new javax.swing.JMenuItem();
        menuAsignarDeducciones = new javax.swing.JMenuItem();
        menuCalculoFinal = new javax.swing.JMenuItem();
        menuAutorizarPolizas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setVisible(true);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        jMenu1.setText("Procesos");

        menuAsignacionPercepciones.setText("Asignacion Percepciones a Empleados");
        menuAsignacionPercepciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAsignacionPercepcionesActionPerformed(evt);
            }
        });
        jMenu1.add(menuAsignacionPercepciones);

        menuAsignarDeducciones.setText("Asignacion Deducciones a Empleados");
        menuAsignarDeducciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAsignarDeduccionesActionPerformed(evt);
            }
        });
        jMenu1.add(menuAsignarDeducciones);

        menuCalculoFinal.setText("Calculo Nomina Final");
        jMenu1.add(menuCalculoFinal);

        menuAutorizarPolizas.setText("Autorizacion de Pólizas");
        jMenu1.add(menuAutorizarPolizas);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void menuAsignacionPercepcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAsignacionPercepcionesActionPerformed
        // TODO add your handling code here:
        AsignacionPercepciones ventana = new AsignacionPercepciones();
        jDesktopPane1.add(ventana);
    }//GEN-LAST:event_menuAsignacionPercepcionesActionPerformed

    private void menuAsignarDeduccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAsignarDeduccionesActionPerformed
        // TODO add your handling code here:
        AsignacionDeducciones ventana = new AsignacionDeducciones();
        jDesktopPane1.add(ventana);
        
    }//GEN-LAST:event_menuAsignarDeduccionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAsignacionPercepciones;
    private javax.swing.JMenuItem menuAsignarDeducciones;
    private javax.swing.JMenuItem menuAutorizarPolizas;
    private javax.swing.JMenuItem menuCalculoFinal;
    // End of variables declaration//GEN-END:variables
}
